#!/usr/bin/env python3
from __future__ import annotations

"""Fast V4.2 launcher with historical V4 warm-start compatibility.

Historical V4 reports predate storing the A-control vector (controls_db). They do
store the resulting A128 FIR and P/K. This launcher projects that saved A128
magnitude response back onto the same 24-point logarithmic A-control grid and
uses it only as an optimization restart.

The projected state is re-evaluated against the current authoritative V4 FIT
evidence and B512 is solved again by distiller_v2_north_star_v42. No stored V4
B512 or score is trusted, and no guitar data enters fitting or candidate choice.
"""

from pathlib import Path

import numpy as np

import train_namtoclo_north_star_v42 as base
from distiller_v2_dsp import A_TAPS, SR, controls_to_a


def controls_from_a128(a128, controls: int):
    """Project a historical A128 FIR onto the current logarithmic control grid.

    V4's A128 was itself generated by controls_to_a(), but V4 did not persist the
    source control vector. Sampling the stored FIR magnitude at the same control
    frequencies gives a close restart in A-response space. This is deliberately
    only a restart approximation: V4.2 immediately re-evaluates it on teacher
    evidence and continues the normal bracket/refine search.
    """
    a = np.asarray(a128, dtype=np.float64)
    if a.shape != (A_TAPS,) or int(controls) < 1 or not np.all(np.isfinite(a)):
        return None

    nfft = 16384
    freqs = np.fft.rfftfreq(nfft, 1.0 / SR)
    response_db = 20.0 * np.log10(np.maximum(np.abs(np.fft.rfft(a, nfft)), 1.0e-12))
    control_freqs = np.geomspace(30.0, 20000.0, int(controls))
    projected = np.interp(control_freqs, freqs, response_db)
    projected = np.clip(projected, -18.0, 18.0)

    # Record an A-response round-trip diagnostic. This never participates in
    # fitting or acceptance; it is only there to make restart quality visible.
    reconstructed = controls_to_a(projected)
    h0 = np.fft.rfft(a, nfft)
    h1 = np.fft.rfft(reconstructed, nfft)
    mask = (freqs >= 30.0) & (freqs <= 20000.0)
    delta_db = 20.0 * np.log10(
        np.maximum(np.abs(h1[mask]), 1.0e-12)
        / np.maximum(np.abs(h0[mask]), 1.0e-12)
    )
    diagnostic = {
        "projection": "A128 magnitude sampled on V4 logarithmic A-control grid",
        "response_rmse_db_30_20k": float(np.sqrt(np.mean(delta_db * delta_db))),
        "response_max_abs_db_30_20k": float(np.max(np.abs(delta_db))),
    }
    return projected.tolist(), diagnostic


def _historical_v4_compatible_warm_start(
    root,
    pair,
    stimulus_manifest,
    levels_db,
    controls,
):
    """Recover a V4 restart when its report has A128 but no controls_db."""
    found = base._find_v3_report(Path(root).expanduser(), pair)
    if found is None:
        return None
    path, report = found

    method = str(report.get("method", "")).lower()
    if not method.startswith(base.V4_FAMILY_METHOD_PREFIXES["V4"].lower()):
        return None

    stimulus = report.get("stimulus") or {}
    if stimulus.get("stimulus_sha256") != stimulus_manifest.get("stimulus_sha256"):
        return None
    try:
        old_levels = tuple(float(v) for v in stimulus.get("levels_db", []))
        new_levels = tuple(float(v) for v in levels_db)
    except Exception:
        return None
    if old_levels != new_levels:
        return None

    pk = report.get("pk")
    if not isinstance(pk, list) or len(pk) != 4:
        return None

    projection = controls_from_a128(report.get("A128"), controls)
    if projection is None:
        return None
    controls_db, projection_diagnostic = projection

    return {
        "source_family": "V4",
        "report_path": str(path),
        "controls_db": controls_db,
        "pk": pk,
        "controls_source": "projected_from_historical_A128",
        "a128_projection_diagnostic": projection_diagnostic,
        "reported_fit_evidence_esr": (
            (report.get("optimizer_fit_evidence_metrics") or {}).get("esr")
        ),
    }


_original_compatible = base._compatible_v4_family_warm_start


def _compatible_with_historical_v4(
    root,
    pair,
    stimulus_manifest,
    levels_db,
    controls,
    family,
):
    # Exact stored controls remain preferred for V4.2/V4.1 and for any newer V4
    # report that happens to contain them.
    exact = _original_compatible(
        root,
        pair,
        stimulus_manifest,
        levels_db,
        controls,
        family,
    )
    if exact is not None:
        exact.setdefault("controls_source", "stored_controls_db")
        return exact
    if family != "V4":
        return None
    return _historical_v4_compatible_warm_start(
        root,
        pair,
        stimulus_manifest,
        levels_db,
        controls,
    )


# Patch only warm-start discovery. All fitting, evidence, objective, DSP,
# calibration, reporting and CLI behavior stay in the authoritative V4.2 trainer.
base._compatible_v4_family_warm_start = _compatible_with_historical_v4


if __name__ == "__main__":
    raise SystemExit(base.main())
